#+TITLE:       Functional TDD
#+AUTHOR:      Bart Post
#+EMAIL:       bart.post@gmail.com
#+DATE:        2015-03-21 za
#+URI:         /blog/%y/%m/%d/functional-tdd
#+KEYWORDS:    tdd, functional
#+TAGS:        tdd
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:{} -:nil f:t *:t <:t
#+DESCRIPTION: A proposal for a more complete outside-in TDD method
#+BEGIN_HTML
---
layout: default
title: Functional TDD
---
#+END_HTML

#+BEGIN_QUOTE
Insert real quote here
#+END_QUOTE

* Problems with TDD

Most examples and guides I found on the internet about TDD and how to
start, have an inside-out work flow: write a test for a class you know
you'll have to write, write code to make the test pass, and refactor.
Then, there are is the outside-in or "London School" way, which
designs all collaborators in a user story up front, and writes [[http://blog.8thlight.com/uncle-bob/2014/05/14/TheLittleMocker.html][test
doubles]] for each collaborator, testing whether the correct methods are
called when a single test case is handled.[fn:5]

Both of these methods have some of the same problems.  I'll try to
elaborate a bit on those here.

** Making up interfaces

Design up front is needed in both situations.  This is not necessarily
a bad thing, but you'll never be as smart and knowledgeable about a
project as by the end of it.  So design up front will in most cases
either mean redesigning as you go, or bending new use cases to the
existing design.  Because changing interfaces and classes comes at a
cost, the second method is usually chosen (adhering to the existing
design).  And to prevent that design from becoming too restricting,
more effort is put into setting up a better design up front, leading
to...

** YAGNI

Bigger designs up front mean designing for things that you're probably
not gonna need anyway.  With inside-out TDD, the most easily
fallen-into trap is: checking for invalid state or invalid request
formats from code that is going to be written by ourselves anyway.
Degenerate use cases that will never occur, may be a good exercise,
but will be a waste of time in the development of many systems.

With outside-in TDD, YAGNI manifests itself in thinking up
collaborators that may or may not have a lot of work to do.  Will you
really need a new interface and a class for behavior that is never
going to be modular?  Will you need an ~IEmailValidator~ in your
~UserAccountController~, and an ~IEmailRegexProvider~ inside that, and
maybe an ~IRegexBuilder~ inside that again?  Or will it be better to
make sure that a request is always in a strongly typed, correctly
formed object?

** Late real composition

The [[http://blog.ploeh.dk/2011/07/28/CompositionRoot/][Composition Root]] is the place in every application where the
inside expectations are finally bound to the outside world.  This is
one of the few, and sometimes only, places, where all external
dependencies are seen alongside each other.  Most of the time, this
happens earlier, in acceptance tests, but more often than not, those
are not really written until after the (test doubles assisted) unit
tests are done.

This is the hardest to test place in the code.  Unit tests should not
interact with the environment, in order to keep them fast.  So using
test doubles for those interactions is a good idea.  The problem is,
when using test doubles, writing the composition root is usually
deferred until deployment testing time.  And as deployment testing is
quite hard, this is not the thing you want to start too late.

Even worse: the composition root being the last one to be written, it
probably has no clear interface.  There may be a config file, but even
that does not really communicate the application's dependencies too
clearly.  And unclear dependencies or requirements are harder to test.

* Starting with the requirement

I've been thinking about software and Test Driven Design for the last
few years.  And last week, refactoring constructor parameters in C#
suddenly seemed an exercise that really resembled partial function
application from F#.  The dependency injection started feeling like
using monads, and [[http://gettingsharper.de/2015/03/10/dependency-injection-a-functional-way/][this insightful blog post]] played no small part in
it.  What if we write tests from the outside in, refactoring into
classes and collaborators as we go?  Is there a way to mock out[fn:1]
the external dependencies in such a way that we make it easier to test
the composition root?

** Collecting initial state, event, and required result

A good user story tells us briefly what the Product Owner wants to see
our system do.  The description in [[http://en.wikipedia.org/wiki/User_story#Format][format]] "As a ... I want ... So that
..." shows what the requirements are at interface level.  When
discussed, a user story should have the [[http://en.wikipedia.org/wiki/INVEST_(mnemonic)][INVEST]] qualities in order to
be accepted into the backlog.  The T in that mnemonic stands for
"Testable".  In [[http://en.wikipedia.org/wiki/Extreme_programming#Values][XP]], the [[http://www.extremeprogramming.org/rules/customer.html][customer]] is expected to take care of the
acceptance tests, written at the system boundaries.  How can we help
the customer to make the requirement testable?

A good test is reproducible.  Therefore, it has a setup phase, making
sure that the system is in a state from which we can verify the
results of the test.  This is quite an important part, and bears a
very big similarity to functional programming in general.[fn:2]
Seeing that the system should respond predictably, we should model
that state as part of the input to the system (which we usually do,
but not as explicitly).

Generally, I believe we should write our requirements into tests like
so:

#+BEGIN_SRC csharp
  public void HandleEvent_WhenGivenStateAndEvent_YieldsExpectedResult()
  {
      Environment initialState = SetupEnvironment(); // To be filled in
      Event eventToHandle = SetupEvent(); // To be filled in, also

      var result = TheApplication.HandleEvent(initialState, eventToHandle);

      Environment expectedState = SetupExpectation(); // Again, to be filled in
      Assert.Equal(expectedState, result);
  }
#+END_SRC

At least, something along these lines.  The ~Environment~ type is the
type that will hold everything that is a given state, and will evolve
as more details about the environment are becoming clear.  It will
hold stubs, mostly, for data that we know should be in the system (in
databases).  It should also hold the state of the user interface, if
it is part of the system.  Anything that resembles state, should be in
that type.  Also, it should be considered immutable during execution
of ~HandleEvent()~.  I will explain why (and how) in the next
sections.

The Event is also very generic.  It should model everything that
models the initiation of the interaction as described in the
requirement.  The reason for this will become clear in the next
section, too.

** Stateless, functional design

If you know about Haskell and the [[https://wiki.haskell.org/IO_inside][IO Monad]], that may help understand
where this is going.  The dependencies that we inject, in the form of
the initialState parameter, form an immutable, trustworthy
representation of the environment.  The Composition Root, which wires
up the environment and calls the HandleEvent function when needed,
should take care of the volatile, possibly violent outside world, and
actually translate each request into something that can be predictably
handled.

The reason I want to have only a single method HandleEvent, instead of
different methods for different requests or events, is that I want
everything outside the tested code to have as little logic as
possible, but I also still want each HandleEvent call to be
responsible for only a single event or request.  If the Environment
would deliver various events, it could no longer be considered
stateless.  If the adapter should route different events to different
handlers, there would be more environment-independent logic inside
this Composition Root[fn:3].

With all the unpredictable stuff moved to this adapter, writing the
inside code needs no longer be overly defensive, focusing on
implementing the requirements instead of handling exceptions,
unforeseen situations, and incomplete data.  The adapter code can now
focus on being testable under different circumstances.[fn:4]

** Wiring up to go live: test driven installation

Installing software is actually nothing more than connecting the
software's expectation to the environmental reality.  In fact, when
testing whether the software is correctly installed, it is not the
installed software that needs to be tested.  That has been covered by
the earlier unit tests already, and extensively so.  Really, the only
thing that has changed and can be in error, is the environment.  And
when looking at it from that perspective, an installation test is
actually an environment test.

Because the Environment type is clear in what it expects, the
installation should make sure that those expectations are met.  This
means that an installation is a function from any environment (no
capital) to either an expected Environment or a clear communication on
what is missing.  Sometimes this requires a lot of configuration,
sometimes it is just reading the last working set of configuration
options and testing them.

You may notice that I am pushing the Composition Root and the
installation software very close together.  As the environment can
change between runs, it should be tested on every startup.  And the
installation should do more or less the same.

It is not yet clear to me, how big this outside adapter part should
be.  But it should be the only part of the software that actually
modifies state, or depends on hidden changes in state.  This means
that the internals of the system, those we write from the
requirements, will be state-free, and should work under all
(explicitly) expected conditions.

* Yet to come

In coming posts, I will focus on writing code driven by a requirement
test.  I also want to dig deeper into the EnvironmentAdapter,
fulfilling the roles of Composition Root, State Handler and
Installation Tester.  Til then!

* Footnotes

[fn:1] Colloquially speaking. I don't really know how to verb "Test
Double".

[fn:2] The similar part of functional programming being the
[[http://c2.com/cgi/wiki?ReferentialTransparency][referential transparency]], here.  Executing the same test 100 times
will yield the same result 100 times.

[fn:3] Actually, I should start calling it the EnvironmentAdapter,
because this code should do more than just wire objects together.

[fn:4] It should probably also have some code to coordinate state
changes to bottleneck state providers.  That is, requests can be
totally independent of their surroundings, and therefore handled
concurrently.  But writes to a database, for instance, should still be
coordinated.  That stuff is stateful, and should lie here, too.  More
on that in later posts.

[fn:5] [[http://martinfowler.com/articles/mocksArentStubs.html][This blog]] by Martin Fowler has a lot of interesting things to
say about "Classical TDD" versus "Mockist TDD", I can recommend the
read!
